apiVersion: v1
kind: Service
metadata:
  name: simple-service-new
spec:
  type: NodePort
  selector:
    app: trivial-go-web-app
  ports:
      - nodePort: 31001
        protocol: TCP
        port: 8080
